[package]
name = "radio-sx128x"
description = "Driver for the Semtec sx1280 2.4GHz RF IC"
version = "0.1.0"
authors = ["Ryan Kurte <ryankurte@gmail.com>"]

[dependencies]
embedded-hal = { version = "0.2.3-rc.1", features = ["unproven"] }
embedded-spi = "0.2.0"
#radio = { path = "../rust-radio" }

futures = "0.1.22"
nb = "0.1.1"
libc = "0.2.42"

[build-dependencies]
bindgen = "0.47.0"
cc = "1.0"
git2 = "0.8.0"

[dev-dependencies]
embedded-hal-mock = { git="https://github.com/ryankurte/embedded-hal-mock", branch="feature/mock-engine" }
color-backtrace = "0.1.3"

[patch.crates-io]
#embedded-hal =  { path = "../embedded-hal" }
#embedded-hal-mock = { path = "../embedded-hal-mock" }
