[package]
name = "radio-sx128x"
description = "Driver for the Semtec sx1280 2.4GHz RF IC"
version = "0.1.0"
authors = ["Ryan Kurte <ryankurte@gmail.com>"]

[dependencies]
embedded-hal = { version = "0.2.2", features=["unproven"] }
futures = "0.1.22"
nb = "0.1.1"
radio = { path = "../rust-radio" }
libc = "0.2.42"


[build-dependencies]
bindgen = "0.47.0"
cc = "1.0"

[dev-dependencies]
embedded-hal-mock = "0.5.0"

[patch.crates-io]
embedded-hal = { git="https://github.com/japaric/embedded-hal", features=["unproven"] }
embedded-hal-mock = { git="https://github.com/ryankurte/embedded-hal-mock", features=["unproven"] }