[package]
authors = ["Ryan Kurte <ryankurte@gmail.com>"]
description = "Driver for the Semtec sx1280 2.4GHz RF IC"
license = "MPL-2.0"
name = "radio-sx128x"
version = "0.11.0"


[features]
default = ["util", "serde"]
util = ["structopt", "linux-embedded-hal", "simplelog", "humantime"]


[dependencies]
bitflags = "1.0.4"
embedded-spi = "0.5.5"
libc = "0.2.42"
log = "0.4.6"
radio = "0.4.0"

[dependencies.strum]
version = "*"
optional = true

[dependencies.strum_macros]
version = "*"
optional = true

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.3"

[dependencies.humantime]
optional = true
version = "1.2.0"

[dependencies.linux-embedded-hal]
optional = true
version = "0.2.2"

[dependencies.serde]
features = ["derive"]
optional = true
version = "1.0"

[dependencies.simplelog]
optional = true
version = "0.5.3"

[dependencies.structopt]
optional = true
version = "0.3.2"

[dev-dependencies]
color-backtrace = "0.1.3"


[[bin]]
name = "sx128x-util"
path = "src/util/main.rs"
required-features = ["util"]
