[package]
authors = ["Ryan Kurte <ryankurte@gmail.com>"]
description = "Driver for the Semtec sx1280 2.4GHz RF IC"
repository = "https://github.com/ryankurte/rust-radio-sx128x"
license = "MPL-2.0"
name = "radio-sx128x"
version = "0.11.3"


[features]
default = ["util", "serde"]
util = ["structopt", "linux-embedded-hal", "simplelog", "humantime", "embedded-spi/utils"]


[dependencies]
bitflags = "1.0.4"
libc = "0.2.42"
log = "0.4.6"
radio = "0.5.0"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.3"

[dependencies.embedded-spi]
version = "0.6.0"
default-features = false

[dependencies.humantime]
optional = true
version = "1.2.0"

[dependencies.linux-embedded-hal]
optional = true
version = "0.3.0"

[dependencies.serde]
features = ["derive"]
optional = true
version = "1.0"

[dependencies.simplelog]
optional = true
version = "0.5.3"

[dependencies.structopt]
optional = true
version = "0.3.2"

[dev-dependencies]
color-backtrace = "0.1.3"


[[bin]]
name = "sx128x-util"
path = "src/util/main.rs"
required-features = ["util"]

[patch.crates-io]
#embedded-spi = { path = "../rust-embedded-spi" }