[package]
name = "radio-sx128x"
description = "Driver for the Semtec sx1280 2.4GHz RF IC"
version = "0.3.1"
authors = ["Ryan Kurte <ryankurte@gmail.com>"]
license = "MPL-2.0"

[features]
util = [ "structopt", "linux-embedded-hal", "simplelog", "humantime" ]
default = [ "util" ]

[dependencies]
libc = "0.2.42"
embedded-hal = { version = "0.2.3", features = ["unproven"] }
embedded-spi = "0.5.5"
radio = "0.3.0"
log = "0.4.6" 
bitflags = "1.0.4"
serde = { version = "1.0", features = ["derive"] }

structopt = { version = "0.2.15", optional = true }
linux-embedded-hal = { version = "0.2.2", optional = true }
simplelog = { version = "0.5.3", optional = true }
humantime = { version = "1.2.0", optional = true }


[dev-dependencies]
color-backtrace = "0.1.3"

[[bin]]
name = "sx128x-util"
path = "src/util/main.rs"
required-features = ["util"]
